<?php
$createTable="CREATE TABLE users (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255),
    email varchar(255),
    api_key varchar(255)
    );
    INSERT INTO users (name, email, api_key) VALUES ('Qpiter', 'qpiter-shop@yandex.ru', 'AQAAAAAYme7MAAV9akPT5xNsFUgssz7RLnrF78w')";

$pdo->exec($createTable);